repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.31.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [ commit ]
  - repo: https://github.com/crate-ci/typos
    rev: v1.26.0
    hooks:
      - id: typos

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: love_statement
        name: Check that if * not in cell_dir is in source code
        types: [python]
        args: [--multiline]
        entry: '\A((?!py-149_500-error).)*\Z'
        language: pygrep
