name: Build container

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      docker_file:
        required: true
        type: string
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
env:
  docker_file:  ${{ inputs.docker_file }}
  TAG:  ${{ inputs.tag }}
  DOCKERHUB_IMAGE_ID: "qcdis/"

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v4

    - name: Free Up GitHub Actions Ubuntu Runner Disk Space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true


    - name: Login to github Registry
      if: ${{ inputs.push }}
      uses: docker/login-action@v3
      with:
        registry: "https://index.docker.io/v1/"
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}

    - id: get_version
      uses: battila7/get-version-action@v2
    - run: echo ${{ steps.get_version.outputs.version }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check and truncate version
      id: check_and_truncate
      run: |
        version=${{ steps.get_version.outputs.version }}
        if [ ${#version} -gt 10 ]; then
          echo "::set-output name=version::${version:0:10}"
        else
          echo "::set-output name=version::$version"
        fi

    - name: Build docker
      uses: docker/build-push-action@v6
      with:
        context: docker/${{ inputs.docker_file }}
        push: ${{ inputs.push }}
        tags: qcdis/${{ inputs.tag }}:${{ steps.check_and_truncate.outputs.version }},qcdis/${{ inputs.tag }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=min