# yaml
name: Run tests

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      debug:
        required: true
        type: string
      verify_ssl:
        required: true
        type: string
      disable_auth:
        required: true
        type: string
      test:
        required: true
        type: string
      pytest_extra_options:
        default: ""
        type: string
    secrets:
      registry_token_for_tests:
        required: true
      cell_github_token:
        required: true

env:
  DEBUG: ${{ inputs.debug }}
  DISABLE_AUTH: ${{ inputs.disable_auth }}
  VERIFY_SSL: ${{ inputs.verify_ssl }}
  REGISTRY_TOKEN_FOR_TESTS: ${{ secrets.registry_token_for_tests }}
  CELL_GITHUB_TOKEN: ${{ secrets.cell_github_token }}


jobs:
  test-minikube-script:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: true
      matrix:
        chart:
          - minikube_tests/charts/argo-workflows-0.33.1-Chart.yaml
    steps:
      - uses: actions/checkout@v6

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          python-version: 3.11
          path: ${{ env.CONDA }}/envs
          environment-file: environment.yaml
          activate-environment: naavre-containerizer-service
          use-mamba: true

      - name: Cache Conda environment
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-environment-${{ runner.os }}-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            conda-environment-${{ runner.os }}-
        id: cache-conda

      - name: start Minikube
        id: minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          addons: ingress,ingress-dns
          minikube-version: '1.38.0'

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Run setup-tests.sh
        shell: bash -l {0}
        run: |
          ./minikube_tests/setup-tests-local.sh -f minikube_tests/values-deploy-naavre-containerizer-service-minikube-github.yaml -d -n -u -p -v -c "${{ matrix.chart }}"

      - name: Install pytest
        run: pip install pytest

      - name: pytest
        shell: bash -l {0}
        run: |
          conda activate naavre-containerizer-service
          pip install pytest
          pytest ${{ inputs.test }} -s --ignore=docker --ignore=cypress --no-header --log-cli-level=DEBUG -vv --tb=long ${{ inputs.pytest_extra_options }}